### ISSUE TITLE
Unable to start trojsten web

### ISSUE THREAD

**Issue by Siegrift** [trojsten/web#1327]
When I run `docker-compose up`, I get an error. I have `git bisect`ed it and the commit which introduced the breakage is https://github.com/trojsten/web/commit/6a60b866a80bb2203b94ba2fde89074c7d5a38c1 (Add nginx docker image for serving static files., @mhozza ).

I don't know what is wrong, but this `2020-04-15 09:37:59.331 UTC [1] FATAL:  database files are incompatible with server` seems to be the culprit. Can you fix this please?

The error trace:
```
db_1     | 
db_1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1     | 
db_1     | 2020-04-15 09:37:59.331 UTC [1] FATAL:  database files are incompatible with server
db_1     | 2020-04-15 09:37:59.331 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 10, which is not compatible with this version 12.2.
login_1  | manage.py:8: UserWarning: Not reading .env - it doesn't exist.
login_1  |   dotenv.read_dotenv()
web_db_1 exited with code 1
web_1    | manage.py:8: UserWarning: Not reading .env - it doesn't exist.
web_1    |   dotenv.read_dotenv()
login_1  | manage.py:8: UserWarning: Not reading .env - it doesn't exist.
login_1  |   dotenv.read_dotenv()
web_1    | manage.py:8: UserWarning: Not reading .env - it doesn't exist.
web_1    |   dotenv.read_dotenv()
login_1  | Performing system checks...
login_1  | 
login_1  | System check identified no issues (0 silenced).
web_1    | Performing system checks...
web_1    | 
web_1    | System check identified no issues (0 silenced).
login_1  | Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7ff877a2a378>
login_1  | Traceback (most recent call last):
login_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
web_1    | Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f2ea6473378>
web_1    | Traceback (most recent call last):
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
login_1  |     self.connect()
login_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
login_1  |     self.connection = self.get_new_connection(conn_params)
login_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
login_1  |     connection = Database.connect(**conn_params)
login_1  |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
web_1    |     self.connect()
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
login_1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
login_1  | psycopg2.OperationalError: could not translate host name "db" to address: Name does not resolve
login_1  | 
login_1  | 
login_1  | The above exception was the direct cause of the following exception:
login_1  | 
login_1  | Traceback (most recent call last):
login_1  |   File "/usr/local/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
web_1    |     self.connection = self.get_new_connection(conn_params)
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
login_1  |     fn(*args, **kwargs)
login_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 120, in inner_run
web_1    |     connection = Database.connect(**conn_params)
web_1    |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
login_1  |     self.check_migrations()
login_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 442, in check_migrations
web_1    |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
web_1    | psycopg2.OperationalError: could not translate host name "db" to address: Name does not resolve
web_1    | 
login_1  |     executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
login_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__
login_1  |     self.loader = MigrationLoader(self.connection)
login_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
web_1    | 
web_1    | The above exception was the direct cause of the following exception:
web_1    | 
login_1  |     self.build_graph()
login_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 212, in build_graph
login_1  |     self.applied_migrations = recorder.applied_migrations()
login_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 61, in applied_migrations
web_1    | Traceback (most recent call last):
login_1  |     if self.has_table():
login_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 44, in has_table
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
web_1    |     fn(*args, **kwargs)
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 120, in inner_run
login_1  |     return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
login_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 255, in cursor
login_1  |     return self._cursor()
login_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 232, in _cursor
web_1    |     self.check_migrations()
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 442, in check_migrations
web_1    |     executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__
login_1  |     self.ensure_connection()
login_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
web_1    |     self.loader = MigrationLoader(self.connection)
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
login_1  |     self.connect()
login_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
web_1    |     self.build_graph()
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/loader.py", line 212, in build_graph
login_1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
login_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
web_1    |     self.applied_migrations = recorder.applied_migrations()
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 61, in applied_migrations
login_1  |     self.connect()
login_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
web_1    |     if self.has_table():
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/migrations/recorder.py", line 44, in has_table
login_1  |     self.connection = self.get_new_connection(conn_params)
login_1  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
web_1    |     return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 255, in cursor
login_1  |     connection = Database.connect(**conn_params)
login_1  |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
web_1    |     return self._cursor()
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 232, in _cursor
web_1    |     self.ensure_connection()
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
web_1    |     self.connect()
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
login_1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
login_1  | django.db.utils.OperationalError: could not translate host name "db" to address: Name does not resolve
login_1  | 
web_1    |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
web_1    |     self.connect()
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 194, in connect
web_1    |     self.connection = self.get_new_connection(conn_params)
web_1    |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
web_1    |     connection = Database.connect(**conn_params)
web_1    |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
web_1    |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
web_1    | django.db.utils.OperationalError: could not translate host name "db" to address: Name does not resolve

```

**Comment by black3r** [comment]
yep, that commit upgraded the postgres version from 10 to 12, you need to upgrade your local DB to use it with the newer version.., probably the simplest solution for you would be to launch the DB with older postgres version, dump all data, drop the DB (`docker-compose down -v`), launch the newer version creating an empty DB and restoring the data into the DB that's already in a new format.

**Comment by mhozza** [comment]
Alternatively, you can just drop the db (or remove the docker volume with db) and import the db from dump, or fixtures again.

**Comment by Siegrift** [comment]
I tried the noob way which I thoough was gonna work. 
1. `sudo rm -rf web`
2. `docker ps --all` a potom `docker rm id1 id2` so vsetkymi, ktore boli related (ostal mi iba jeden, ktore pouzivam v praci)
3. naklonujem repo znovu.
4. Idem podla https://github.com/trojsten/web/wiki/N%C3%A1vod-na-in%C5%A1tal%C3%A1ciu
5. V kroku 5, `docker-compose up` mi vyhubuje:
```
PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1     | 
db_1     | 2020-04-18 09:22:08.763 UTC [1] FATAL:  database files are incompatible with server
db_1     | 2020-04-18 09:22:08.763 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 10, which is not compatible with this version 12.2.
...
```

Did I do something wrong? I thought after removing all docker containers + doing fresh clone would solve this issue.
cc: @molcan23

**Comment by mhozza** [comment]
Skus `docker volume rm trojsten_db_data` alebo ako sa vola ta particia.
Michal Hozza

**Comment by Siegrift** [comment]
Thanks @mhozza , works for me now. Please try to merge https://github.com/trojsten/web/pull/1325 so that the setup works from master.
